export function ImportPlantRequestDTO(data) {
    return {
        name: data.name ?? '',
        country: data.country ?? null,
        latitude: data.latitude != null ? parseFloat(data.latitude) : null,
        longitude: data.longitude != null ? parseFloat(data.longitude) : null,
        status: data.status ?? 'DRAFT',
        capacity: data.capacity != null ? parseFloat(data.capacity) : null,
        constructionDurationYears: data.constructionDurationYears != null ? parseInt(data.constructionDurationYears) : null,
        description: data.description ?? null,
        soilType: data.soilType ?? null,
        waterSourceType: data.waterSourceType ?? null,
        seismicStability: data.seismicStability != null ? parseFloat(data.seismicStability) : null,
        floodRisk: data.floodRisk != null ? parseFloat(data.floodRisk) : null,
        groundwaterLevel: data.groundwaterLevel != null ? parseFloat(data.groundwaterLevel) : null,
        waterProximity: data.waterProximity != null ? parseFloat(data.waterProximity) : null,
        waterFlowRate: data.waterFlowRate != null ? parseFloat(data.waterFlowRate) : null,
        populationDensity: data.populationDensity != null ? parseFloat(data.populationDensity) : null,
        transportInfrastructureScore: data.transportInfrastructureScore != null ? parseFloat(data.transportInfrastructureScore) : null,
        geologicalRiskScore: data.geologicalRiskScore != null ? parseFloat(data.geologicalRiskScore) : null,
        numberOfReactors: data.numberOfReactors != null ? parseInt(data.numberOfReactors) : null,
        estimatedEfficiency: data.estimatedEfficiency != null ? parseFloat(data.estimatedEfficiency) : null,
        operationalRiskLevel: data.operationalRiskLevel != null ? parseFloat(data.operationalRiskLevel) : null,
        reactorConfigurations: Array.isArray(data.reactorConfigurations) ? data.reactorConfigurations : [],
        safetySystems: Array.isArray(data.safetySystems) ? data.safetySystems : [],
        reactors: Array.isArray(data.reactors) ? data.reactors.map(r => ({
            reactorCode: r.reactorCode ?? '',
            reactorType: r.reactorType ?? '',
            coolingType: r.coolingType ?? '',
            thermalPowerMw: r.thermalPowerMw != null ? parseFloat(r.thermalPowerMw) : null,
            electricalPowerMw: r.electricalPowerMw != null ? parseFloat(r.electricalPowerMw) : null,
        })) : [],
    };
}
