export function ReactorRequestDTO({
    powerPlantId,
    reactorCode,
    reactorType,
    coolingType,
    operationalStatus,
    thermalPowerMw,
    electricalPowerMw,
    fuelCycleDays,
    currentCycleDay,
    wearIndex,
    designLifetimeYr,
    commissioningDate,
    firstCriticality,
    lastInspectionAt,
    nextPlannedOutage,
    description,
}) {
    return {
        powerPlantId: powerPlantId || undefined,
        reactorCode: reactorCode || undefined,
        reactorType: reactorType || undefined,
        coolingType: coolingType || undefined,
        operationalStatus: operationalStatus || undefined,
        thermalPowerMw: thermalPowerMw !== '' && thermalPowerMw != null ? parseFloat(thermalPowerMw) : null,
        electricalPowerMw: electricalPowerMw !== '' && electricalPowerMw != null ? parseFloat(electricalPowerMw) : null,
        fuelCycleDays: fuelCycleDays !== '' && fuelCycleDays != null ? parseInt(fuelCycleDays) : null,
        currentCycleDay: currentCycleDay !== '' && currentCycleDay != null ? parseInt(currentCycleDay) : null,
        wearIndex: wearIndex !== '' && wearIndex != null ? parseFloat(wearIndex) : null,
        designLifetimeYr: designLifetimeYr !== '' && designLifetimeYr != null ? parseInt(designLifetimeYr) : null,
        commissioningDate: commissioningDate || null,
        firstCriticality: firstCriticality || null,
        lastInspectionAt: lastInspectionAt || null,
        nextPlannedOutage: nextPlannedOutage || null,
        description: description || null,
    };
}
