CREATE TYPE sensor_types AS ENUM (
    'THERMOCOUPLE', 'PRESSURE_TRANSDUCER', 'NEUTRON_DETECTOR',
    'FLOW_METER', 'RADIATION_MONITOR', 'VIBRATION_SENSOR',
    'LEVEL_SENSOR', 'ACTIVITY_MONITOR', 'SEISMIC_SENSOR',
    'HYDROGEN_DETECTOR', 'VALVE_POSITION', 'PUMP_SPEED'
);
 
CREATE TYPE sensor_quality AS ENUM (
    'GOOD', 'SUSPECT', 'BAD', 'MAINTENANCE', 'SIMULATED'
);