<?php
require_once __DIR__ . '/../../PHPMailer/src/Exception.php';
require_once __DIR__ . '/../../PHPMailer/src/PHPMailer.php';
require_once __DIR__ . '/../../PHPMailer/src/SMTP.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

class EmailService {

    public function __construct() {}

    public function sendAlert(array $data): bool {
        $toEmail = $data['to_email'] ?? '';
        $subject = $data['subject'] ?? 'Registry System Alert';
        $message = $data['message'] ?? '';

        if (empty($toEmail) || empty($message)) {
            throw new Exception("Incomplete data: to_email and message are required fields.");
        }

    
        $host = getenv('MAIL_HOST');
        $port = getenv('MAIL_PORT');
        $user = getenv('MAIL_USER');
        $pass = getenv('MAIL_PASS'); 

        $phpmailer = new PHPMailer(true); 
        LogService::instance()->debug("[DEBUG_MAIL] USER CITIT: " . getenv('MAIL_USER'));
        LogService::instance()->debug("[DEBUG_MAIL] PASS CITIT: " . (getenv('MAIL_PASS') ? 'Are valoare' : 'E VID'));
        try {
            $phpmailer->isSMTP();
            $phpmailer->Host       = $host;
            $phpmailer->SMTPAuth   = true;
            $phpmailer->Port       = $port;
            $phpmailer->Username   = $user;
            $phpmailer->Password   = $pass;
            $phpmailer->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            $phpmailer->CharSet    = 'UTF-8';

        
            $phpmailer->setFrom('system@nuclear-plant.local', 'Plant Alert System');
            $phpmailer->addAddress($toEmail);

            $phpmailer->isHTML(true);
            $phpmailer->Subject = $subject;
            
            $phpmailer->Body = "
                <div style='font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4;'>
                    <div style='max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 30px; border-radius: 8px; border-left: 5px solid #ff3333;'>
                        <h2 style='color: #333333; margin-top: 0;'>Power Plant System Alert</h2>
                        <p style='color: #555555; font-size: 14px; line-height: 1.6;'>
                            " . nl2br(htmlspecialchars($message)) . "
                        </p>
                        <hr style='border: 0; border-top: 1px solid #eeeeee; margin: 20px 0;'>
                        <p style='font-size: 11px; color: #999999; margin-bottom: 0;'>
                            This is an automated message generated by the local application.
                        </p>
                    </div>
                </div>
            ";

            $phpmailer->send();
            LogService::instance()->debug("[DEBUG][EMAIL_SERVICE] Email successfully sent to " . $toEmail);
            return true;

        } catch (Exception $e) {
      
            LogService::instance()->error("[ERROR][EMAIL_SERVICE] SMTP transfer failed: " . $phpmailer->ErrorInfo);
            throw new Exception("Error sending email via SMTP server: " . $phpmailer->ErrorInfo);
        }
    }
}