CREATE TABLE IF NOT EXISTS admin_data_entries (
    id SERIAL PRIMARY KEY,
    entry_type VARCHAR(50) NOT NULL DEFAULT 'reactor_report',
    plant_name VARCHAR(150) NOT NULL,
    reactor_code VARCHAR(50) NOT NULL,
    country VARCHAR(100) NOT NULL,
    soil_type VARCHAR(100),
    risk_level SMALLINT CHECK (risk_level BETWEEN 1 AND 5),
    efficiency NUMERIC(5,2) CHECK (efficiency BETWEEN 0 AND 100),
    status VARCHAR(50) NOT NULL,
    weather VARCHAR(100),
    wear_level SMALLINT CHECK (wear_level BETWEEN 1 AND 5),
    planned_maintenance BOOLEAN NOT NULL DEFAULT false,
    unplanned_stop BOOLEAN NOT NULL DEFAULT false,
    notes TEXT,
    metrics CLOB NOT NULL CHECK (metrics IS JSON),
    created_by VARCHAR(100) NOT NULL DEFAULT 'admin',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
