export const SensorType = [
    { value: "THERMOCOUPLE", label: "Termocuplu" },
    { value: "PRESSURE_TRANSDUCER", label: "Senzor de presiune" },
    { value: "NEUTRON_DETECTOR", label: "Detector de neutroni" },
    { value: "FLOW_METER", label: "Debitmetru" },
    { value: "RADIATION_MONITOR", label: "Monitor de radiații" },
    { value: "VIBRATION_SENSOR", label: "Senzor de vibrații" },
    { value: "LEVEL_SENSOR", label: "Senzor de nivel" },
    { value: "ACTIVITY_MONITOR", label: "Monitor de activitate" },
    { value: "SEISMIC_SENSOR", label: "Senzor seismic" },
    { value: "HYDROGEN_DETECTOR", label: "Detector de hidrogen" },
    { value: "VALVE_POSITION", label: "Poziție valvă" },
    { value: "PUMP_SPEED", label: "Viteză pompă" },
];

export const SensorQuality = [
    { value: "GOOD", label: "Bună" },
    { value: "SUSPECT", label: "Suspectă" },
    { value: "BAD", label: "Rea" },
    { value: "MAINTENANCE", label: "În mentenanță" },
    { value: "SIMULATED", label: "Simulată" },
];

export const MeasurementField = [
    { value: "", label: "-- Fără câmp --" },
    { value: "power_percent", label: "Putere (%)" },
    { value: "neutron_flux", label: "Flux neutronic" },
    { value: "temp_coolant_in", label: "Temperatură agent intrare" },
    { value: "temp_coolant_out", label: "Temperatură agent ieșire" },
    { value: "temp_fuel_center", label: "Temperatură combustibil" },
    { value: "temp_moderator", label: "Temperatură moderator" },
    { value: "pressure", label: "Presiune" },
    { value: "steam_pressure", label: "Presiune abur" },
    { value: "flow_rate_primary", label: "Debit primar" },
    { value: "flow_rate_secondary", label: "Debit secundar" },
    { value: "steam_flow_rate", label: "Debit abur" },
    { value: "activity_primary", label: "Activitate agent primar" },
    { value: "dose_rate_control_room", label: "Doza sală comandă" },
    { value: "dose_rate_reactor_bldg", label: "Doza clădire reactor" },
    { value: "level_reactor_vessel", label: "Nivel vas reactor" },
    { value: "feedwater_temp", label: "Temperatură apă alimentare" },
    { value: "radiation", label: "Radiație" },
    { value: "airborne_activity", label: "Activitate aer" },
    { value: "reactivity_pcm", label: "Reactivitate (pcm)" },
    { value: "reactor_period_sec", label: "Perioadă reactor (s)" },
    { value: "fuel_burnup_mwd_t", label: "Ardere combustibil" },
    { value: "efficiency", label: "Eficiență" },
    { value: "wear_delta", label: "Variație uzură" },
];
