CREATE TYPE reactor_operational_status AS ENUM ( 
    'SHUTDOWN', 'COLD_STANDBY', 'HOT_STANDBY', 'STARTUP',
    'POWER_ASCENT', 'FULL_POWER', 'PARTIAL_POWER',
    'PLANNED_OUTAGE', 'UNPLANNED_OUTAGE', 'EMERGENCY_SHUTDOWN'
); 

CREATE TYPE reactor_types AS ENUM (
    'PWR', 'BWR', 'PHWR', 'FBR'
);

CREATE TYPE cooling_types AS ENUM (
    'ONCE_THROUGH_FRESH', 'ONCE_THROUGH_SALT', 'NATURAL_DRAFT_WET',       
    'MECHANICAL_DRAFT_WET', 'DRY_COOLING', 'HYBRID', 'COOLING_POND'             
);

